version: 2.1

orbs:
  semantic-release: trustedshops-public/semantic-release@6.0.0

workflows:
  version: 2
  continious:
    jobs:
      - semantic-release/with_existing_config:
          name: semantic-release
          additional_packages: "@google/semantic-release-replace-plugin"
          context:
            - github-release
          filters:
            branches:
              only: [main]
