version: 2.1

orbs:
  semantic-release: trustedshops-public/semantic-release@3.1.5

workflows:
  version: 2
  continious:
    jobs:
      - semantic-release/with-changelog-github-config:
          name: semantic-release
          context:
            - github-release
          filters:
            branches:
              only: [main]
